---
cli:
  host: "{{ inventory_hostname }}"
  username: "{{ nxos_cli_user | default('admin') }}"
  password: "{{ nxos_cli_pass | default('admin') }}"
  transport: cli

nxapi:
  host: "{{ inventory_hostname }}"
  username: "{{ nxos_eapi_user | default('admin') }}"
  password: "{{ nxos_eapi_pass | default('admin') }}"
  transport: nxapi
  use_ssl: no


