---
- hosts: nxos
  gather_facts: no
  connection: local
  vars:
    testcase: "{{ test_case | default('') }}"
    limitto: "{{ limit_to | default('') }}"
    test_cases:
        - files: []
  roles:

    # use -e"limit_to=foo" to run a specific set of tests only
    # use -tags "cli" -e"limit_to=foo testcase=bar" to run a specific test case

    - { role: test_nxos_command, delegate_to: virl, when: "limitto == '' or limitto == 'command'" }
    - { role: test_nxos_section, delegate_to: virl, when: "limitto == '' or limitto == 'section'" }
    - { role: test_nxos_config, delegate_to: virl, when: "limitto == '' or limitto == 'config'" }
    - { role: test_nxos_nxapi, debug: no, delegate_to: virl, when: "limitto == '' or limitto == 'nxapi'" }
