---
- name: Test backup file creation 
  hosts: nxos
  connection: local
  tasks:
    - debug: msg="START - TEST BACKUPS IN PLAYBOOK CONTEXT" 

    - command: echo "${PWD}"
      register: pwd
    
    - name: collect any backup files in PWD
      find:
        paths: "{{ pwd.stdout_lines[0] }}/backup"
        pattern: "{{ inventory_hostname }}_config*"
      register: backup_files
      delegate_to: localhost
    
    - name: delete backup files from PWD 
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: backup_files.files
      delegate_to: localhost 

    - name: collect any backup files in playbook dir
      find:
        paths: "./backup"
        pattern: "{{ inventory_hostname }}_config*"
      register: backup_files
      delegate_to: localhost
    
    - name: delete backup files from playbook dir
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: backup_files.files
      delegate_to: localhost 
    
    - name: configure device and create backup 
      nxos_template:
        src: roles/test_nxos_template/templates/basic/config.j2
        backup: yes
        provider: "{{ cli }}"
      register: result
      delegate_to: virl   
    
    - name: collect any backup files in playbook dir
      find:
        paths: "./backup"
        pattern: "{{ inventory_hostname }}_config*"
      register: backup_files
      delegate_to: localhost
    
    - assert:
        that:
          - "backup_files.files is defined"

    - name: collect any backup files in PWD" 
      find:
        paths: "{{ pwd.stdout_lines[0] }}/backup"
        pattern: "{{ inventory_hostname }}_config*"
      register: backup_files
      delegate_to: localhost

    - assert:
        that:
          - "backup_files.files | length == 0"

    - debug: msg="END - TEST BACKUPS IN PLAYBOOK CONTEXT" 
