---
- name: configure test interface
  nxos_section:
    commands:
      - no description
      - no shutdown
    parents:
      - interface Ethernet2/5
    provider: "{{ cli }}"
    strategy: force

- name: configure nxos using cli
  nxos_config:
    src: config.j2
    provider: "{{ cli }}"
  register: nxos_config

- assert:
    that:
      - "nxos_config.changed == true"
      - "nxos_config.failed == false"

- name: configure nxos use cli idempotent check
  nxos_config:
    src: config.j2
    provider: "{{ cli }}"
  register: nxos_config

- assert:
    that:
      - "nxos_config.changed == false"
      - "nxos_config.failed == false"





